In [1]:
import pandas as pd

In [2]:
import pandas as pd
df = pd.read_csv("shipment_data.csv")
df["Delivery_Time"] = df.groupby("Region")["Delivery_Time"].transform(lambda x:x.fillna(x.mean()))
df.head()

  Shipment_ID Region  Delivery_Time
0     SHP1000   East           72.0
1     SHP1001   West           36.0
2     SHP1002  North           48.0
3     SHP1003   East           60.0
4     SHP1004   East           24.0

In [4]:
import pandas as pd
df = pd.read_csv("shipment_data.csv")
df["Delivery_Time"] = df.groupby("Region")["Delivery_Time"].transform(lambda x:x.fillna(x.mean()))
df.head()

  Shipment_ID Region  Delivery_Time
0     SHP1000   East           72.0
1     SHP1001   West           36.0
2     SHP1002  North           48.0
3     SHP1003   East           60.0
4     SHP1004   East           24.0

In [5]:
df.rename(columns={'Region': 'New_Region'}, inplace=True)

In [7]:
df.head()

  Shipment_ID New_Region  Delivery_Time
0     SHP1000       East           72.0
1     SHP1001       West           36.0
2     SHP1002      North           48.0
3     SHP1003       East           60.0
4     SHP1004       East           24.0

In [9]:
df.shape

(50, 3)

In [2]:
import pandas as pd

In [3]:
#1. Create DataFrame
df = pd.DataFrame([11,22,33],columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [5]:
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
data = {
    'Name': ['Madhav','Vishaka','Lalita','Rishabh'],
    'Age': [23,19,24,18],
    'Salary': [90000,89000,78000,56000]
}

In [7]:
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0   Madhav   23   90000
1  Vishaka   19   89000
2   Lalita   24   78000
3  Rishabh   18   56000

#2. Basic DataFrame Understanding

In [8]:
df.head(2)

      Name  Age  Salary
0   Madhav   23   90000
1  Vishaka   19   89000

In [9]:
df.tail(2)

      Name  Age  Salary
2   Lalita   24   78000
3  Rishabh   18   56000

In [12]:
df.shape

(4, 3)

In [13]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [14]:
df.rename(columns={'Salary':'Monthly_Salary'})

      Name  Age  Monthly_Salary
0   Madhav   23           90000
1  Vishaka   19           89000
2   Lalita   24           78000
3  Rishabh   18           56000

In [15]:
df

      Name  Age  Salary
0   Madhav   23   90000
1  Vishaka   19   89000
2   Lalita   24   78000
3  Rishabh   18   56000

In [16]:
df.rename(columns={'Salary':'Monthly_Salary'},inplace=True)

In [17]:
df

      Name  Age  Monthly_Salary
0   Madhav   23           90000
1  Vishaka   19           89000
2   Lalita   24           78000
3  Rishabh   18           56000

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [19]:
df.describe()

            Age  Monthly_Salary
count   4.00000        4.000000
mean   21.00000    78250.000000
std     2.94392    15798.206649
min    18.00000    56000.000000
25%    18.75000    72500.000000
50%    21.00000    83500.000000
75%    23.25000    89250.000000
max    24.00000    90000.000000

#3 . Save and Load data From csv

In [20]:
df.to_csv('Test_data.csv')

In [22]:
load_df = pd.read_csv('Test_data.csv')
load_df

   Unnamed: 0     Name  Age  Monthly_Salary
0           0   Madhav   23           90000
1           1  Vishaka   19           89000
2           2   Lalita   24           78000
3           3  Rishabh   18           56000

#4.Rows and Columns - Selection

In [24]:
#df[['Name']] - Single Column
df[['Name','Monthly_Salary']]

      Name  Monthly_Salary
0   Madhav           90000
1  Vishaka           89000
2   Lalita           78000
3  Rishabh           56000

In [ ]:
# select rows (loc - Index name based)
# loc - label based index
# df.loc[df.Name=='Madhav']
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=50000)]

     Name  Age  Monthly_Salary
0  Madhav   23           90000

In [28]:
# iloc - index-value based
# df.iloc(0)
df.iloc[0:2]

      Name  Age  Monthly_Salary
0   Madhav   23           90000
1  Vishaka   19           89000

5.Filter Dataframe

In [29]:
df

      Name  Age  Monthly_Salary
0   Madhav   23           90000
1  Vishaka   19           89000
2   Lalita   24           78000
3  Rishabh   18           56000

In [ ]:
#df['Age'] > 15 - Gives Boolean Value ture,False
df[df['Age'] > 15]

      Name  Age  Monthly_Salary
0   Madhav   23           90000
1  Vishaka   19           89000
2   Lalita   24           78000
3  Rishabh   18           56000

In [35]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 80000)]

      Name  Age  Monthly_Salary
0   Madhav   23           90000
1  Vishaka   19           89000

In [37]:
df.where(df['Age'] >= 20)

     Name   Age  Monthly_Salary
0  Madhav  23.0         90000.0
1     NaN   NaN             NaN
2  Lalita  24.0         78000.0
3     NaN   NaN             NaN

In [38]:
df.where(df['Age'] >= 20, other = 'Not Eligible')

           Name           Age Monthly_Salary
0        Madhav            23          90000
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            24          78000
3  Not Eligible  Not Eligible   Not Eligible

6. Rows and Columns Operations

In [ ]:
# add new column
df['Team'] = ['CEO','HR','DSP','SDE']
df

      Name  Age  Monthly_Salary Team
0   Madhav   23           90000  CEO
1  Vishaka   19           89000   HR
2   Lalita   24           78000  DSP
3  Rishabh   18           56000  SDE

In [40]:
df['Bonus'] = df['Monthly_Salary']*0.2

In [41]:
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   23           90000  CEO  18000.0
1  Vishaka   19           89000   HR  17800.0
2   Lalita   24           78000  DSP  15600.0
3  Rishabh   18           56000  SDE  11200.0

In [43]:
# add new row
df.loc[len(df)] = ['ABC',21, 34000,'IT',6800]
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   23           90000  CEO  18000.0
1  Vishaka   19           89000   HR  17800.0
2   Lalita   24           78000  DSP  15600.0
3  Rishabh   18           56000  SDE  11200.0
4      ABC   21           34000   IT   6800.0
5      ABC   21           34000   IT   6800.0

In [44]:
len(df)

6

In [ ]:
# update value using index value
df.loc[0,'Monthly_Salary'] = 95000
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   23           95000  CEO  18000.0
1  Vishaka   19           89000   HR  17800.0
2   Lalita   24           78000  DSP  15600.0
3  Rishabh   18           56000  SDE  11200.0
4      ABC   21           34000   IT   6800.0
5      ABC   21           34000   IT   6800.0

In [46]:
# update value - using column name
df.loc[df.Name == 'Madhav','Monthly_Salary'] = 90000

In [47]:
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   23           90000  CEO  18000.0
1  Vishaka   19           89000   HR  17800.0
2   Lalita   24           78000  DSP  15600.0
3  Rishabh   18           56000  SDE  11200.0
4      ABC   21           34000   IT   6800.0
5      ABC   21           34000   IT   6800.0

In [50]:
# Delete Value - rowa and columns value

df.drop(df[df.Name == 'ABC'].index)  # drop row axis = 0.

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   23           90000  CEO  18000.0
1  Vishaka   19           89000   HR  17800.0
2   Lalita   24           78000  DSP  15600.0
3  Rishabh   18           56000  SDE  11200.0

In [ ]:
df.drop('Bonus',axis=1,inplace=True)
#df.drop(['Bonus','Team'],axis = 1) - Delete multiole columns

In [54]:
df.drop(1,axis=0) #index name

      Name  Age  Monthly_Salary Team
0   Madhav   23           90000  CEO
2   Lalita   24           78000  DSP
3  Rishabh   18           56000  SDE
4      ABC   21           34000   IT
5      ABC   21           34000   IT

In [55]:
# sort value

df.sort_values('Monthly_Salary')

      Name  Age  Monthly_Salary Team
5      ABC   21           34000   IT
4      ABC   21           34000   IT
3  Rishabh   18           56000  SDE
2   Lalita   24           78000  DSP
1  Vishaka   19           89000   HR
0   Madhav   23           90000  CEO

# working with date value

In [64]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-05','2024-04-23','2024-06-24']
df

      Name  Age  Monthly_Salary Team         DOJ
0   Madhav   23           90000  CEO  2024-01-01
1  Vishaka   19           89000   HR  2024-01-15
2   Lalita   24           78000  DSP  2024-03-28
3  Rishabh   18           56000  SDE  2024-03-05
4      ABC   21           34000   IT  2024-04-23
5      ABC   21           34000   IT  2024-06-24

In [66]:
df['DOJ'].dtype

In [67]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [68]:
df['DOJ'].dtype

dtype('<M8[us]')

In [71]:
# extract year,month,week,day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3     Tuesday
4     Tuesday
5      Monday
Name: DOJ, dtype: str

In [73]:
df['Month'] = df['DOJ'].dt.month
df

      Name  Age  Monthly_Salary Team        DOJ  Month
0   Madhav   23           90000  CEO 2024-01-01      1
1  Vishaka   19           89000   HR 2024-01-15      1
2   Lalita   24           78000  DSP 2024-03-28      3
3  Rishabh   18           56000  SDE 2024-03-05      3
4      ABC   21           34000   IT 2024-04-23      4
5      ABC   21           34000   IT 2024-06-24      6

In [74]:
df['DOJ'] + pd.Timedelta(days=90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-03
4   2024-07-22
5   2024-09-22
Name: DOJ, dtype: datetime64[us]

# Handling Missing Values

In [75]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ  Month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False           False  False  False  False
4  False  False           False  False  False  False
5  False  False           False  False  False  False

In [76]:
import numpy as np

In [77]:
df.loc[df.Name=='Rishabh','Salary'] = np.nan

In [78]:
df

      Name  Age  Monthly_Salary Team        DOJ  Month  Salary
0   Madhav   23           90000  CEO 2024-01-01      1     NaN
1  Vishaka   19           89000   HR 2024-01-15      1     NaN
2   Lalita   24           78000  DSP 2024-03-28      3     NaN
3  Rishabh   18           56000  SDE 2024-03-05      3     NaN
4      ABC   21           34000   IT 2024-04-23      4     NaN
5      ABC   21           34000   IT 2024-06-24      6     NaN

In [80]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ  Month  Salary
0  False  False           False  False  False  False    True
1  False  False           False  False  False  False    True
2  False  False           False  False  False  False    True
3  False  False           False  False  False  False    True
4  False  False           False  False  False  False    True
5  False  False           False  False  False  False    True

# Aggregation and Group-By

In [82]:
df['Month'].value_counts()

Month
1    2
3    2
4    1
6    1
Name: count, dtype: int64

In [ ]:
df[df['Month']==3].value_counts()

      Name  Age  Monthly_Salary Team        DOJ  Month  Salary
0   Madhav   23           90000  CEO 2024-01-01      1     NaN
1  Vishaka   19           89000   HR 2024-01-15      1     NaN
2   Lalita   24           78000  DSP 2024-03-28      3     NaN
3  Rishabh   18           56000  SDE 2024-03-05      3     NaN
4      ABC   21           34000   IT 2024-04-23      4     NaN
5      ABC   21           34000   IT 2024-06-24      6     NaN

In [88]:
df.groupby('Month')['Monthly_Salary'].sum()  # aggregation based on groupby

Month
1    179000
3    134000
4     34000
6     34000
Name: Monthly_Salary, dtype: int64

In [89]:
df.groupby('Month').agg({'Monthly_Salary':'mean','Name': 'count'})

       Monthly_Salary  Name
Month
1             89500.0     2
3             67000.0     2
4             34000.0     1
6             34000.0     1

# concatenatee and merge dataframe(JOINS)

In [90]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [91]:
df2 = pd.DataFrame({'ID':[1,2,3,4],'Score':[88,99,77,79]})
df2

   ID  Score
0   1     88
1   2     99
2   3     77
3   4     79

In [ ]:
# Vertical / Row Level / top on top
pd.concat([df1,df2],axis = 0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   99.0
2   3  NaN   77.0
3   4  NaN   79.0

In [93]:
# Horizontal/Column level / Side on Side
pd.concat([df1,df2],axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     99
2  3.0    C   3     77
3  NaN  NaN   4     79

In [ ]:
# merge = join (inner,left,right,outer)
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     99
2   3    C     77

In [95]:

pd.merge(df1,df2,how='inner',left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     99
2   3    C     77